## Heart Attack Risk Prediction Dataset Generated by CHATGPT :  Sourav BANERJEE , kaggle  
##https://www.kaggle.com/datasets/iamsouravbanerjee/heart-attack-prediction-dataset 

library(dplyr)
df<- read.csv("https://dl.dropboxusercontent.com/scl/fi/81s470lw7qksgii98zp5z/heart_attack_prediction_dataset.csv?rlkey=ujciqitahvvtqm73t8t1v7bhx&dl=1",header = TRUE,sep=',')
str(df)


#######################################################################################################################################
# Les variables quantitatives : Age , Cholesterol | Heart Rate | Exercise Hours per Week

# Les variables qualitatives ; * Nominal: Catégorique Binaire ::  Medication use|Previous Heart Problem | Alcohol Consumption | obesity
#                              * Heart attack Risk*

#######################################################################################################################################
## Conversion des variables binaire as.factor 

col_convert <- c("Diabetes","Family.History","Smoking","Obesity","Alcohol.Consumption","Previous.Heart.Problems","Medication.Use","Heart.Attack.Risk","Diet","Sex")
for (col in col_convert) {
  df[[col]] <- as.factor(df[[col]])
}
str(df)

## Création d'une nouvelle colonne avec 3 levels (Hypertension | Hypotension et Normal) pour la tension artérielle
df$Blood.Pressure
df$Blood.Pressure <- sapply(df$Blood.Pressure, function(bp) {
  systolic <- as.numeric(gsub("/.*", "", bp))
  diastolic <- as.numeric(gsub(".*/", "", bp))
  
  if (systolic <= 120 && diastolic <= 80) {
    return("Normal")
  } else if (systolic > 140 || diastolic > 90) {
    return("Hypertension")
  } else {
    return("Hypotension")
  }
}) %>% as.factor()

################################################################################################################
##############################################  Age  ###########################################################
# paramètre de position
mean(df$Age)
median(df$Age)
quantile(df$Age, probs = c(0.25, 0.5,0.75))

# paramètre de dispertion

sd(df$Age)
max(df$Age)
min(df$Age)
range(df$Age)
IQR(df$Age)

# Preview using box plot
boxplot(df$Age)

#commentaires :
#ensemble de données sur l'âge semble être relativement symétrique,
#avec un âge moyen de 53,71 ans, et une quantité modérée de variabilité
#(comme indiqué par l'écart type). La plage d'âges va de 18 à 90 ans, 
#et les quartiles et l'IQR offrent des informations sur la distribution
#des âges dans votre ensemble de données.


##################################  BMI ##################################################
# paramètre de position
mean(df$BMI)
median(df$BMI)
quantile(df$BMI, probs = c(0.25, 0.5,0.75))

# paramètre de dispertion

sd(df$BMI)
max(df$BMI)
min(df$BMI)
range(df$BMI)
IQR(df$BMI)

# Preview using box plot
boxplot(df$BMI)



## commentaires :
#données sur l'IMC montre une distribution légèrement asymétrique avec une moyenne 
#d'environ 28,89. La plage de l'IMC va de 18,00 à 39,99, et les quartiles 
#et l'écart type fournissent des informations sur la distribution 
#de l'IMC dans votre ensemble de données.

#######################################################################################################
#                                                                                                     #
#                               VARIABLES QUALITATIVES                                                #
#                                                                                                     #
#######################################################################################################
###############################    Heart Attack Risk  #################################################

table(df$Heart.Attack.Risk)
table(df$Heart.Attack.Risk) %>% prop.table()*100

ggplot(df, aes(x=Heart.Attack.Risk)) + geom_bar()


#######################################     Sex   #####################################################
table(df$Sex) #summary(df$Sex)
prop.table(table(df$Sex))*100

ggplot(df, aes(x = Sex)) + geom_bar()


#######################################     Blood pressure   #################################################

table(df$Blood.Pressure) # summary(df$Blood.Pressure)
prop.table(table(df$Blood.Pressure))*100

ggplot(df, aes(x = Blood.Pressure)) + geom_bar()

##############################################################################################################
#######################################################################################################
#                                                                                                     #
#                               Croisement de variable  QUALI | QUALI                                 #
#                                                                                                     #
#######################################################################################################
# SEX & DIABETES

prop.table(table(df$Heart.Attack.Risk, df$Blood.Pressure),1) ## ligne ie: proportion des gens avec Hypertension  dans la population '' low heart attack risk"
prop.table(table(df$Heart.Attack.Risk, df$Blood.Pressure),2) ## colonne ie: proportion des gens avec "low heart attack risk :0 " dans la population ''Hypertension''
prop.table(table(df$Heart.Attack.Risk, df$Blood.Pressure)) ## table ie : proportion des gens avec Hypertension et low heart attack risk dans la population totale.
#install.packages("gmodels") 
library(gmodels)
CrossTable(df$Heart.Attack.Risk, df$Blood.Pressure, prop.chisq = FALSE)

library(ggplot2)
ggplot(data = df, aes(x = Blood.Pressure, fill = Heart.Attack.Risk )) +
  geom_bar()




#######################################################################################################
#                                                                                                     #
#                               Croisement de variable  QUALI | QUANTI                                #
#                                                                                                     #
#######################################################################################################
# Age | Heart attack risk
######################################################

mean(df$Age[which(df$Heart.Attack.Risk==1)])
mean(df$Age[which(df$Heart.Attack.Risk==0)])
by(df$Age, df$Heart.Attack.Risk, mean)
# using package
#install.packages("doBy")
library(doBy)
summaryBy(Age ~ Heart.Attack.Risk, data = df)
boxplot(Age ~ Heart.Attack.Risk, data = df, xlab = "Heart Attack Risk", ylab = "Age", main = "Heart Attack Risk By Age")

# UN PLUS:
#######################################################################################################
#                                                                                                     #
#                               Croisement de variable  Qaunti | Quanti                               #
#                                                                                                     #
#######################################################################################################
cor(df$Age, df$Physical.Activity.Days.Per.Week)

# Croisement de plusieurs variables Quantitatives en utilisant corrplot package
# Corelation Matrix 
Num_data <- df[, c("Age","Cholesterol","Heart.Rate","Exercise.Hours.Per.Week","Sedentary.Hours.Per.Day",
                   "Income","BMI","Triglycerides","Physical.Activity.Days.Per.Week","Sleep.Hours.Per.Day")]
cor(Num_data)
correlation_matrix <- cor(Num_data)


# install.packages("corrplot")

library(corrplot)
corrplot(
  correlation_matrix,
  method = "color",
  is.corr = TRUE,
  tl.col = "Black",
  col = colorRampPalette(c("white", "Red"))(100),
  tl.srt = 90,
  tl.cex = 0.8,
  addgrid.col = "Black"
)

