---
title: "R Notebook"
output: html_notebook
---


# Exemple d'entrainement d'algorithme de classification : 

## Jeu de données utilisé BreastCancer : 

```{r}
library(mlbench)
data(BreastCancer)
BDD<- BreastCancer
BDD<- BDD[!duplicated(BDD$Id),]
BDD<- BDD[complete.cases(BDD),]
```


## Description rapide des données

```{r}
library(skimr)
skim(BDD)
```
```{r}
table(BDD$Class)

```


## Garder un jeu de données de test de côté

```{r}
set.seed(10)
ran <- sample(1:nrow(BDD), 0.9 * nrow(BDD)) 
BDD_train  <- BDD[ran,]
BDD_test  <-  BDD[-ran,]

dim(BDD_test)
dim(BDD_train)


```

## Vérification de la randomisation

```{r}
prop.table(table(BDD_train$Class))
prop.table(table(BDD_test$Class))

```

## Randomisation stratifiée

```{r}
library(dplyr)
set.seed(10)
id_Train <-BDD %>%
    group_by(Class) %>%
    slice_sample(prop=0.9)%>%pull(Id)
BDD_train  <- BDD[BDD$Id %in% id_Train,]
BDD_test  <-  BDD[!BDD$Id %in% id_Train,]

```


```{r}

prop.table(table(BDD_train$Class))
prop.table(table(BDD_test$Class))

```





## Regression logistique simple

```{r}
names(BDD_train)
BDD_train<-BDD_train%>%select(-Id)
```


```{r}
fit <- glm(Class~Cl.thickness+Cell.size, data=BDD_train,family = "binomial")
summary(fit)
```


```{r}
predict(fit,BDD_train)%>%head
```


```{r}
predict(fit,BDD_train,type = "response")%>%head
table(predict(fit,BDD_train,type = "response")>0.5)
table(predict(fit,BDD_train)>0)

y_pred=predict(fit,BDD_train,type = "response")

plot(y_pred[order(y_pred)])
```


```{r}
table(predict(fit,BDD_train)>0,BDD_train$Class)
table(predict(fit,BDD_train,type = "response")>0.5,BDD_train$Class)

```
```{r}
fit3 <-  glm(Class~., data=BDD_train,family = "binomial")
#summary(fit3)
table(predict(fit3,BDD_train)>0,BDD_train$Class)
```
```{r}
table(predict(fit3,BDD_test)>0,BDD_test$Class)
table(predict(fit,BDD_test)>0,BDD_test$Class)
```



```{r}
fit2 <- glm(Class~., data=
              BDD_train%>%mutate_at(vars(Cl.thickness:Epith.c.size), function(x) as.numeric(as.character(x)))
            ,family = "binomial")
fit2
```


```{r}
table(predict(fit2,
              BDD_train%>%mutate_at(vars(Cl.thickness:Epith.c.size), function(x) as.numeric(as.character(x))))>0
      ,BDD_train$Class)

```
```{r}
table(predict(fit2,BDD_test%>%mutate_at(vars(Cl.thickness:Epith.c.size), function(x) as.numeric(as.character(x))))>0,BDD_test$Class)
```



```{r}
accuracy<- function(table_contingence){
round(sum(diag(table_contingence))/
sum(table_contingence)*100,1)
}
accuracy(table(predict(fit3,BDD_train)>0,BDD_train$Class))
```
```{r}
table(c(T,T),c(F,F))
accuracy(table(c(T,T),c(F,F)))
```


## Cross validation

### Modèle 2 variables vs toutes : 

```{r, warning=F}


```

```{r warning=F}
set.seed(12)
n_folds=5
samples<- sample(size = nrow(BDD_train),
                 x = cut(1:nrow(BDD_train),
                                                 n_folds,labels=FALSE))
# samples
acc_res_1<- acc_res_2 <- c()

for(i in 1:n_folds){
  BDD_train_i <- BDD_train[!samples==i,]
  BDD_test_i <- BDD_train[samples==i,]

  fit_cv <- glm(Class~Cl.thickness+Cell.size, data=BDD_train_i,family = "binomial")
y_pred <- predict(fit_cv,BDD_test_i)>0
  acc_res_1 <- c(acc_res_1,accuracy(table(y_pred ,BDD_test_i$Class=="malignant" )))

  fit_cv2 <- glm(Class~., data=BDD_train_i%>%select(-Epith.c.size),family = "binomial")
y_pred2  <- predict(fit_cv2,BDD_test_i)>0
acc_res_2 <- c(acc_res_2,accuracy(table(y_pred2 ,BDD_test_i$Class=="malignant" )))

  
  
}

mean(acc_res_1)
acc_res_1
mean(acc_res_2)
acc_res_2
```



### Autre modèle

```{r, warning=F}


res6<- res6_train<- c()
for(sample_i in 1:n_folds){
  
  BDD_train_i= BDD_train[!samples ==sample_i,]
  BDD_test_i= BDD_train[samples ==sample_i,]
  
BDD_train_i =BDD_train_i%>%mutate_at(vars(Cl.thickness:Epith.c.size), function(x) as.numeric(as.character(x)))

  BDD_test_i<-BDD_test_i%>%mutate_at(vars(Cl.thickness:Epith.c.size), function(x) as.numeric(as.character(x)))
  
  fit6 <-  glm(Class~., data=BDD_train_i,family = "binomial")
  
    acc_train <- accuracy(table(predict(fit6,BDD_train_i)>0,BDD_train_i$Class))
  res6_train<- c(res6_train,acc_train)
  
  acc<- accuracy(table(predict(fit6,BDD_test_i)>0,BDD_test_i$Class))
  res6<- c(res6,acc)
  
}


```

```{r}
mean(res6_train)
mean(res6)
```

## CV le seuil ? 

  
```{r}
library(ggplot2)
res6_data_frame<- data.frame()
for(sample_i in n_folds){

  BDD_train_i= BDD_train[!samples ==sample_i,]
  BDD_test_i= BDD_train[samples ==sample_i,]
BDD_train_i =BDD_train_i%>%mutate_at(vars(Cl.thickness:Epith.c.size), function(x) as.numeric(as.character(x)))
  BDD_test_i<-BDD_test_i%>%mutate_at(vars(Cl.thickness:Epith.c.size), function(x) as.numeric(as.character(x)))
  
  fit6 <-  glm(Class~., data=BDD_train_i,family = "binomial")
  
     for( seuil in seq(0,1,0.1)){
  acc<- accuracy(table(
    predict(fit6,BDD_test_i,type = "response")>seuil,
    BDD_test_i$Class))
  res6_data_frame<- rbind(res6_data_frame,
                          data.frame(seuil=as.character(seuil), acc=acc)
  )
  }
}
res6_data_frame
res6_data_frame%>%ggplot(aes(fill=seuil, y=acc))+geom_boxplot()
```

```{r}
399/629
table(BDD$Class, rep("benign",629))
```



  
```{r}

VPP = function(y_pred, y){ return((sum(y_pred & y)/sum(y_pred))*100)}
VPN = function(y_pred, y){ return((sum(! y_pred&! y)/sum(!y_pred))*100)}
rappel = function(y_pred, y){ return((sum( y_pred& y)/sum(y))*100)}


res6_data_frame<- data.frame()
for(sample_i in 1:n_folds){

  BDD_train_i= BDD_train[!samples ==sample_i,]
  BDD_test_i= BDD_train[samples ==sample_i,]
BDD_train_i =BDD_train_i%>%mutate_at(vars(Cl.thickness:Epith.c.size), function(x) as.numeric(as.character(x)))
  BDD_test_i<-BDD_test_i%>%mutate_at(vars(Cl.thickness:Epith.c.size), function(x) as.numeric(as.character(x)))
  
  fit6 <-  glm(Class~., data=BDD_train_i,family = "binomial")
  
     for( seuil in seq(0,1,0.1)){
       y_pred = predict(fit6,BDD_test_i,type = "response")>seuil
       y_vrai = as.numeric(BDD_test_i$Class)==2
  acc<- accuracy(table(y_pred, y_vrai))
  res6_data_frame<- rbind(res6_data_frame,
                          data.frame(seuil=as.character(seuil), acc=acc,
                                     VPP = VPP(y_pred,y_vrai),
                                     VPN = VPN(y_pred,y_vrai),
                                     rappel = rappel(y_pred,y_vrai)
  )
  )
  }
}
library(tidyr)
res6_data_frame <- res6_data_frame%>%mutate(F1 = 2*VPP*rappel/(rappel+VPP))
res6_data_frame%>%pivot_longer(cols = -seuil, names_to = "type",values_to = "score")%>%ggplot(aes(fill=seuil,x=type, y=score))+geom_boxplot()
```



```{r}
res6_data_frame%>%ggplot(aes(y=F1, x = seuil
                         )) +geom_violin()
```



```{r}
readRDS("data_test.rds")
```


